ansible_ssh_user: admin
ansible_ssh_pass: admin
ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
ansible_network_os: sros
ansible_host_key_auto_add: yes
ansible_host_key_checking: False
